### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by rbits0** [Magisk-Modules-Repo/airmusic#8]
Could you please make a release, because the beta version of Magisk doesn't support installing modules directly from the repo anymore, so there is no way to install this on Magisk beta.

**Comment by funtax** [comment]
Hey @rbits0 , many thanks for the hints, I didn't recognize your ticket earlier.
I am not able to find any note/instructions/change-nodes or similar, could you tell me a link for this?

Thanks in advance and kind regards.

**Comment by guythnick** [comment]
Also having an "Unzip error" when trying to manually install the zip file in Magisk Canary.   They have removed installing modules via the app.  I am not sure if this needs to be built first, but it is not installing when I manually install the git zip from storage in Magisk app. 

[Related Magisk issue](https://github.com/topjohnwu/Magisk/issues/4939)
